[package]
name = "hammer_time"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "=0.29.0" # 0.31.0 now has a critical bug with TextEdit 
catppuccin-egui = { version = "5.4.0", default-features = false, features = ["egui29"] }
egui-theme-switch = "=0.2.1"
rfd = "0.15"
serde = { version = "1.0.218", features = ["derive"] }
log = "0.4.26"
fern = "0.7"


[build-dependencies]
winresource = "0.1.19"

[lints.rust]
unused = { level = "allow", priority = -1 } # For exploratory dev.
