[package]
name = "vmflow_config_types"
version.workspace = true
edition.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
compiler_data_model.workspace = true
compilers_service.workspace = true
serde.workspace = true