[package]
name = "compiler_data_model"
version.workspace = true
edition.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
serde = { version = "1.0.218", features = ["derive"] }
