[package]
name = "compilation_core"
version.workspace = true
edition.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
async-std = "1.13.1"
async-lock = "3.4.0"
async-process = "2.3.1"
futures = "0.3.31"
vmflow_config_types.workspace = true
